"""Command line interface: ``pma serve | generate | demo | eval | retrieve``."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from dataclasses import replace
from importlib import resources
from pathlib import Path

from pma import __version__
from pma.config import Settings
from pma.errors import PMAError
from pma.logging_setup import configure_logging
from pma.schemas import AgentResult, ProductInput

_LANG_NAMES = {"en": "ENGLISH", "nl": "NEDERLANDS"}


def format_result(result: AgentResult) -> str:
    u = result.usage
    lines = [
        f"Status: {result.status.upper()}  (iterations={result.iterations}, "
        f"llm_calls={u.llm_calls}, tokens={u.total_tokens}{'~' if u.tokens_estimated else ''}, "
        f"latency={result.latency_ms:.0f} ms, provider={result.provider}/{result.model})",
        "",
    ]
    if result.draft:
        for lang in result.draft.languages():
            content = result.draft.get(lang)
            assert content is not None
            lines += [f"== {_LANG_NAMES[lang]} ==", f"Description : {content.description}"]
            lines += [f"Ad copy     : {content.ad_copy}", f"Social post : {content.social_post}"]
            lines += [f"Subject {i}   : {s}" for i, s in enumerate(content.email_subjects, 1)]
            lines.append("")
    lines += ["-- Why --", result.report.summary]
    if result.report.checks_passed:
        lines.append("Checks passed : " + ", ".join(result.report.checks_passed))
    if result.report.checks_failed:
        lines.append("Checks failed : " + ", ".join(result.report.checks_failed))
    for reason in result.report.judge_reasons:
        lines.append(f"Judge         : {reason}")
    for rev in result.report.revisions:
        lines.append(f"Revision after iteration {rev.iteration}:")
        lines += [f"  - {p}" for p in rev.problems]
    if result.security.injection_detected:
        lines.append(
            "SECURITY: suspected prompt injection in the input (removed before the model):"
        )
        lines += [f"  - {f.field}: {f.rule}: {f.snippet}" for f in result.security.findings]
    for warning in result.report.data_warnings:
        lines.append(f"Data warning  : {warning}")
    if result.report.guidelines_used:
        lines.append("Guidelines    : " + ", ".join(result.report.guidelines_used))
    if result.trace_path:
        lines.append(f"Trace         : {result.trace_path}")
    return "\n".join(lines)


def _examples() -> list[ProductInput]:
    raw = (resources.files("pma") / "data" / "examples.json").read_text(encoding="utf-8")
    return [ProductInput.model_validate(x) for x in json.loads(raw)]


def _agent_for(settings: Settings):
    from pma.agent import MarketingAgent
    from pma.providers import build_provider

    return MarketingAgent(build_provider(settings), settings)


# --------------------------------------------------------------------------- commands


def cmd_serve(args: argparse.Namespace) -> int:
    import uvicorn

    uvicorn.run("pma.api:app_factory", factory=True, host=args.host, port=args.port)
    return 0


def cmd_generate(args: argparse.Namespace) -> int:
    settings = Settings.from_env()
    configure_logging(settings.log_level, settings.log_format)
    if args.file:
        product = ProductInput.model_validate_json(Path(args.file).read_text(encoding="utf-8"))
    else:
        examples = _examples()
        names = {p.id: p for p in examples}
        if args.example not in names:
            print(
                f"unknown example {args.example!r}; choose from {', '.join(names)}", file=sys.stderr
            )
            return 2
        product = names[args.example]
    languages = [x.strip() for x in args.languages.split(",") if x.strip()]
    result = _agent_for(settings).run(product, languages)
    print(
        json.dumps(result.model_dump(mode="json"), indent=2) if args.json else format_result(result)
    )
    return 0 if result.passed else 1


def cmd_demo(args: argparse.Namespace) -> int:
    out = Path(args.out) if args.out else None
    trace_dir = (out / "traces") if out else Path(tempfile.mkdtemp(prefix="pma-demo-"))
    settings = Settings.from_env(
        {
            "LLM_PROVIDER": "mock",
            "MOCK_BEHAVIOR": "demo",
            "TRACE_DIR": str(trace_dir),
        }
    )
    configure_logging("WARNING", "text")
    agent = _agent_for(settings)
    by_id = {p.id: p for p in _examples()}
    sections: list[str] = [
        "# Demo output (mock provider)",
        "",
        "Generated by `pma demo`. The text below is written by the rule-based **simulated** model "
        "(`SimulatedMarketingLLM`), not by a language model. What is real is the pipeline around "
        "it: planning with tool calls, evaluation, feedback, revision, and the report.",
        "",
    ]
    traces: dict[str, str] = {}
    for pid in ("demo-3", "demo-1", "demo-2"):
        product = by_id[pid]
        result = agent.run(product)
        text = format_result(result)
        print(f"\n######## {product.name} ########\n{text}")
        shown = "\n".join(line for line in text.splitlines() if not line.startswith("Trace"))
        sections += [f"## {product.name}", "", "```text", shown, "```", ""]
        if result.trace_path:
            traces[pid] = result.trace_path
    if out:
        out.mkdir(parents=True, exist_ok=True)
        (out / "demo_output.md").write_text("\n".join(sections), encoding="utf-8")
        shutil.copyfile(traces["demo-3"], out / "sample_trace.json")
        shutil.rmtree(trace_dir, ignore_errors=True)
        print(f"\nwrote {out / 'demo_output.md'} and {out / 'sample_trace.json'}")
    return 0


def cmd_eval(args: argparse.Namespace) -> int:
    from pma.dataset import load_cases
    from pma.evaluation import render_markdown, run_comparison
    from pma.providers import build_provider
    from pma.providers.mock import MockProvider

    csv_path = Path(args.csv)
    if not csv_path.is_file():
        print(f"CSV not found: {csv_path}", file=sys.stderr)
        return 2
    cases = load_cases(csv_path)
    if args.limit:
        cases = cases[: args.limit]
    if args.provider == "mock":
        settings = Settings.from_env({"LLM_PROVIDER": "mock", "TRACE_DIR": tempfile.mkdtemp()})
        provider = MockProvider(
            flaw_scripts={c.product.id or "": c.mock_script for c in cases},
            behavior="clean",
            record_requests=False,
        )
        heading = "Evaluation results - MOCK provider (scripted simulation, not a real model)"
        note = (
            "These numbers come from the simulated mock provider with flaws scripted in "
            "`evals/products.csv`. They show that the pipeline detects, reports and repairs the "
            "scripted failure types; they say nothing about real model quality."
        )
    else:
        settings = replace(Settings.from_env(), trace_dir=Path(tempfile.mkdtemp()))
        if settings.llm_provider == "mock":
            print("set LLM_PROVIDER to a real provider for --provider env", file=sys.stderr)
            return 2
        provider = build_provider(settings)
        heading = f"Evaluation results - REAL provider {settings.llm_provider}"
        note = f"Single run, small sample (n={len(cases)}): treat differences as indicative only."
    configure_logging("WARNING", "text")
    report = run_comparison(
        cases,
        provider,
        settings,
        progress=(lambda m: print(m, file=sys.stderr)) if args.verbose else None,
    )
    report.notes.append(note)
    markdown = render_markdown(report, heading)
    print(markdown)
    if args.out:
        out = Path(args.out)
        out.mkdir(parents=True, exist_ok=True)
        (out / "results.md").write_text(markdown, encoding="utf-8")
        (out / "results.json").write_text(report.to_json(), encoding="utf-8")
        print(f"wrote {out / 'results.md'} and {out / 'results.json'}", file=sys.stderr)
    return 0


def cmd_retrieve(args: argparse.Namespace) -> int:
    from pma.rag.retriever import build_retriever

    settings = Settings.from_env()
    retriever = build_retriever(settings)
    for hit in retriever.search(args.query, args.k):
        print(f"[{hit.score:.3f}] {hit.chunk.ref}\n{hit.chunk.text}\n")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="pma", description="Product Marketing Agent")
    parser.add_argument("--version", action="version", version=f"pma {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("serve", help="run the API and web page")
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=8000)
    p.set_defaults(func=cmd_serve)

    p = sub.add_parser("generate", help="generate copy for one product")
    src = p.add_mutually_exclusive_group()
    src.add_argument("--file", help="JSON file with a product")
    src.add_argument("--example", default="demo-3", help="built-in example id (default demo-3)")
    p.add_argument("--languages", default="en,nl")
    p.add_argument("--json", action="store_true", help="print the full result as JSON")
    p.set_defaults(func=cmd_generate)

    p = sub.add_parser("demo", help="run the offline mock demo")
    p.add_argument("--out", help="write demo_output.md and sample_trace.json into this directory")
    p.set_defaults(func=cmd_demo)

    p = sub.add_parser("eval", help="baseline vs agent comparison on the CSV products")
    p.add_argument("--csv", default="evals/products.csv")
    p.add_argument("--provider", choices=["mock", "env"], default="mock")
    p.add_argument("--limit", type=int, default=0, help="only the first N products")
    p.add_argument("--out", help="directory for results.md / results.json")
    p.add_argument("--verbose", action="store_true")
    p.set_defaults(func=cmd_eval)

    p = sub.add_parser("retrieve", help="search the brand guidelines")
    p.add_argument("query")
    p.add_argument("-k", type=int, default=3)
    p.set_defaults(func=cmd_retrieve)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.func(args))
    except PMAError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
